azs:
- name: az1
  cpi: lab
  cloud_properties:
    datacenters:
    - clusters: [cluster: {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 10240 
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: az1
  vm_type: large
  network: labnet
